name: build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    if: github.repository == 'charmbracelet/catwalk'
    uses: charmbracelet/meta/.github/workflows/build.yml@main
    with:
      go-version: ""
      go-version-file: ./go.mod
